services:
  - type: web
    name: slp-backend
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app.main:app
    build:
      env:
        pythonVersion: 3.11.6
